Add validation of metric label names Add ability to specify textfile directories Add usage Complete implementation

diff --git a/templates/promrun.sh.j2 b/templates/promrun.sh.j2
--- a/templates/promrun.sh.j2
+++ b/templates/promrun.sh.j2
@@ -1,9 +1,9 @@
 #!/bin/bash
 
 # The "promrun" script runs and monitors a specified command
-#
-# 'sponge' isn't used as a temporary file is required by the GNU 'time'
-# command
+
+# "promrun" is a wrapper around the GNU 'time' command and principally
+# returns statistics generated by 'time'
 
 # Author: MesaGuy (https://github.com/mesaguy)
 # Source: https://github.com/mesaguy/ansible-prometheus/tree/master/templates/promrun.sh.j2
@@ -24,40 +24,93 @@ else
     TEXTFILE_DIRECTORY="/etc/prometheus/node_exporter_textfiles"
 fi
 
+RE_LABEL_NAME="^[a-zA-Z_][a-zA-Z0-9_]*$"
 RE_METRIC_NAME="^[a-zA-Z_:][a-zA-Z0-9_:]*$"
 
+function add_label () {
+    LABELS="$1"
+    LABEL="$2"
+    KEY=$(echo $LABEL | cut -d '=' -f 1)
+    if [[ ! $KEY =~ $RE_LABEL_NAME ]] ; then
+        echo "Label name \"$KEY\" must match regex: $RE_LABEL_NAME" >&2
+        exit 2
+    fi
+    LABELS="$LABELS,$KEY=\"$(echo $LABEL | cut -d "=" -f 2-)\""
+    echo "$LABELS"
+}
+
 function usage () {
-    echo "USAGE"
+    echo "Usage: $(basename $0) [ -Dhv ] [ -d DESCRIPTION ] [ -l label_name=LABEL_VALUE ]"
+    echo "                      [ -n NAME ] [ -s USERNAME ] COMMAND"
+    echo
+    echo "NAME (-n) and COMMAND are required and must be specified after arguments"
+    echo
+    echo " Options:"
+    echo "    -d                         Optional description"
+    echo "    -D                         Enable dryrun mode"
+    echo "    -h                         Print usage"
+    echo "    -l label_name=label_value  Optionally add specified labels to node_exporter"
+    echo "                               textfile data (May be specified multiple times)"
+    echo "    -n NAME                    Required metric name suffix, all metrics are"
+    echo "                               prefixed with 'promrun_'"
+    echo "    -s USERNAME                Optionally Setup textfile directory file"
+    echo "                               permissions for specified username. Must be run"
+    echo "                               as root. Run in dryrun mode to inspect changed"
+    echo "    -t                         Specify a textfiles directory (Defaults"
+    echo "                               to: $TEXTFILE_DIRECTORY)"
+    echo "    -v                         Enable verbose mode"
+    echo
+    echo "Basic example creating $TEXTFILE_DIRECTORY/promrun_ls_test.prom:"
+    echo "promrun -n ls_test ls"
+    echo
+    echo "Example with description and custom labels:"
+    echo "promrun -n ls_test -l environment=\"Production Environment\" -l test=true -d \"ls command test\" ls"
     echo
     exit 1
 }
 
+function end_time_text () {
+    printf "# HELP ${NAME}_endtime Start time in Unix time with microseconds.
+# TYPE ${NAME}_endtime gauge
+${NAME}_endtime{$LABELS} $(date +%s%3N)\n"
+}
+
+function start_time_text () {
+    printf "# HELP ${NAME}_starttime Start time in Unix time with microseconds.
+# TYPE ${NAME}_starttime gauge
+${NAME}_starttime{$LABELS} $(date +%s%3N)\n"
+}
+
 # read the option and store in the variable, $option
-while getopts "Dhl:n::s:v" option; do
+while getopts "d:Dhl:n:s:t:v" option; do
     case ${option} in
         d)
-	        DESCRIPTION="$OPTARG"
+            DESCRIPTION="$OPTARG"
             ;;
         D)
-	        DRYRUN=1
+            DRYRUN=1
             ;;
         h)
-	        usage
+            usage
             ;;
         l)
-            LABELS="$LABELS,$(echo $OPTARG | cut -d '=' -f 1)=\"$(echo $OPTARG | cut -d "=" -f 2-)\""
+            LABELS=$(add_label "$LABELS" "$OPTARG")
+            if [ "$?" -ne "0" ] ; then exit 2 ; fi
             ;;
         n)
-	        NAME="${OPTARG}"
+            NAME="${OPTARG}"
             ;;
         s)
-	        SETUP_USER="$OPTARG"
+            SETUP_USER="$OPTARG"
+            ;;
+        t)
+            TEXTFILE_DIRECTORY="${OPTARG}"
             ;;
         v)
-	        VERBOSE=1
+            VERBOSE=1
             ;;
         \?)
-	        usage
+            usage
             ;;
     esac
 done
@@ -67,18 +120,17 @@ if [ -z "$NAME" ] ; then
     exit 2
 fi
 
-if [ -z "$HAS_TIME" ] ; then
-    echo "'time' command must be in PATH" >&2
-    exit 2
-fi
-
 # Set USER variable if undefined
 if [ -z "$USER" ] ; then
     USER=$(whoami)
 fi
 
 # Remove any prefixed ',' characters from $LABELS, add 'user' label
-LABELS="${LABELS#,},user=\"${USER}\""
+if [ -n "$LABELS" ] ; then
+    LABELS="${LABELS#,},user=\"${USER}\""
+else
+    LABELS="user=\"${USER}\""
+fi
 TEXTFILE_PATH="${TEXTFILE_DIRECTORY}/promrun_${NAME}.prom"
 NAME="promrun_${NAME}"
 
@@ -94,18 +146,26 @@ if [ -n "$SETUP_USER" ] ; then
     if [ -n "$DRYRUN" ] ; then
         echo "[DRYRUN] touch \"$TEXTFILE_PATH\" \"${TEXTFILE_PATH}.tmp\" && chown $SETUP_USER \"$TEXTFILE_PATH\" \"${TEXTFILE_PATH}.tmp\""
     else
+        if [ -n "$VERBOSE" ] ; then
+            echo "touch \"$TEXTFILE_PATH\" \"${TEXTFILE_PATH}.tmp\" && chown $SETUP_USER \"$TEXTFILE_PATH\" \"${TEXTFILE_PATH}.tmp\""
+        fi
         touch "$TEXTFILE_PATH" "${TEXTFILE_PATH}.tmp" && chown $SETUP_USER "$TEXTFILE_PATH" "${TEXTFILE_PATH}.tmp"
     fi
     exit 0
 fi
 
-if [ -n "$DESCRIPTION" ] ; then
-    LABELS="$LABELS,description=\"$DESCRIPTION\""
+if [ -z "${@:$OPTIND:1}" ] ; then
+    echo "A command to run must be specified" >&2
+    exit 2
 fi
 
-if [ -n "$DRYRUN" ] ; then
-    echo "Dry-run is not supported outside of the setup (-s) argument" >&2
+if [ -z "$HAS_TIME" ] ; then
+    echo "'time' command must be in PATH" >&2
     exit 2
+fi
+
+if [ -n "$DESCRIPTION" ] ; then
+    LABELS="${LABELS},description=\"$DESCRIPTION\""
 fi
 
 if [[ ! $NAME =~ $RE_METRIC_NAME ]] ; then
@@ -113,9 +173,6 @@ if [[ ! $NAME =~ $RE_METRIC_NAME ]] ; then
     exit 2
 fi
 
-printf "# HELP ${NAME}_starttime Start time in Unix time with microseconds.
-# TYPE ${NAME}_starttime gauge
-${NAME}_starttime{$LABELS} $(date +%s%3N)\n" > ${TEXTFILE_PATH}.tmp
 TIME_FORMAT="# HELP ${NAME}_cpu_kernel_mode_seconds Total number of CPU-seconds that the process spent in kernel mode.
 # TYPE ${NAME}_cpu_kernel_mode_seconds gauge
 ${NAME}_cpu_kernel_mode_seconds{$LABELS} %S
@@ -140,7 +197,7 @@ ${NAME}_signals_delivered_to_process_count{$LABELS} %k
 # HELP ${NAME}_context_switch_count_involuntary_count Number of times the process was context-switched involuntarily (because the time slice expired).
 # TYPE ${NAME}_context_switch_count_involuntary_count gauge
 ${NAME}_context_switch_count_involuntary_count{$LABELS} %c
-# HELP ${NAME}_context_switch_count_voluntary_count Number of waits: times that the program was context-switched voluntarily, for instance while waiting for an I/O operation to complete.
+# HELP ${NAME}_context_switch_count_voluntary_count Number of waits, times that the program was context-switched voluntarily, for instance while waiting for an I/O operation to complete.
 # TYPE ${NAME}_context_switch_count_voluntary_count gauge
 ${NAME}_context_switch_count_voluntary_count{$LABELS} %w
 # HELP ${NAME}_filesystem_inputs_count Number of filesystem inputs by the process.
@@ -180,18 +237,24 @@ ${NAME}_minor_page_fault_count{$LABELS} %R
 # TYPE ${NAME}_command gauge
 ${NAME}_command{$LABELS,command=\"%C\"} 1"
 
-$GNU_TIME_COMMAND --append --output="${TEXTFILE_PATH}.tmp" --format="$TIME_FORMAT" ${@:$OPTIND}
-EXIT=$?
-printf "# HELP ${NAME}_endtime Start time in Unix time with microseconds.
-# TYPE ${NAME}_endtime gauge
-${NAME}_endtime{$LABELS} $(date +%s%3N)\n" >> ${TEXTFILE_PATH}.tmp
-
-if [ -n "$VERBOSE" ] ; then
-    cat ${TEXTFILE_PATH}.tmp
+if [ -z "$DRYRUN" ] ; then
+    start_time_text > "${TEXTFILE_PATH}.tmp"
+    $GNU_TIME_COMMAND --append --output="${TEXTFILE_PATH}.tmp" --format="$TIME_FORMAT" ${@:$OPTIND}
+    EXIT=$?
+    end_time_text >> "${TEXTFILE_PATH}.tmp"
+    # Copy contents of temporary file to permanent path
+    cp -fp "${TEXTFILE_PATH}.tmp" "$TEXTFILE_PATH"
+    if [ -n "$VERBOSE" ] ; then
+        cat "${TEXTFILE_PATH}.tmp"
+    fi
+else
+    start_time_text | sed 's/^/\[DRYRUN\] /g' >&2
+    TIME_FORMAT=$(echo -e "$TIME_FORMAT" | sed 's/^/\[DRYRUN\] /g')
+    $GNU_TIME_COMMAND --format="$TIME_FORMAT" ${@:$OPTIND}
+    EXIT=$?
+    echo "[DRYRUN] cp -fp \"${TEXTFILE_PATH}.tmp\" \"$TEXTFILE_PATH\"" >&2
+    end_time_text | sed 's/^/\[DRYRUN\] /g' >&2
 fi
-
-# Copy contents of temporary file to permanent path
-cp -p "${TEXTFILE_PATH}.tmp" "$TEXTFILE_PATH"
 
 # Return same exit signal of subprocess
 exit $EXIT
